#!/bin/bash

sudo service postgresql start

sudo -u postgres psql

DROP TABLE IF EXISTS `github_events`;
CREATE TABLE `github_events` (
    `event_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`event_id`),
)
